app:
  hosts:
    appserver:
      ansible_host: 158.160.20.140
  vars:
      ansible_user: "ubuntu"
      ansible_ssh_private_key_file: "~/.ssh/ubuntu"
      ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
db:
  hosts:
    dbserver:
      ansible_host: 10.25.120.11
  vars:
      ansible_user: "ubuntu"
      ansible_ssh_private_key_file: "~/.ssh/ubuntu"
      ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
